from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[3]

DATA_DIR = PROJECT_ROOT / "data"

STATE_FILE = DATA_DIR / "state.json"
CONFIG_FILE = DATA_DIR / "config.json"
USERS_ROLES_FILE = DATA_DIR / "users_roles.json"
TELEMETRY_FILE = DATA_DIR / "telemetry.json"
JOURNAL_FILE = DATA_DIR / "journal.log"

KAFKA_BOOTSTRAP_SERVERS = "kafka:9092"

DEFAULT_GATEWAY_ID = "GATEWAY-1"
DEFAULT_COMPARTMENT_ID = "COMPARTMENT-1"
DEFAULT_DOCKING_PORT_ID = "DOCKING-PORT-1"
DEFAULT_OPERATOR_ID = "OPERATOR-1"
DEFAULT_EARTH_CONTROL_ID = "EARTH-CONTROL-1"
DEFAULT_SHIP_ID = "SHIP-1"